name: "Build Plugin"

on:
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.THE_GH_RELEASE_TOKEN || github.token }}

      - name: "Setup Tools"
        uses: ./.github/actions/setup-tools

      - name: "Copy README.md in root"
        run: cp README.md README.md.original

      - name: "Build Packages"
        run: npm run build

      - name: "Check README.md changes"
        run: |
          if ! cmp --silent README.md README.md.original; then
            echo "Detected README.md changes; Do 'npm run build' to update the docs."
            exit 1
          fi
