name: "Lint Plugin"

on: 
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  lint:
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.THE_GH_RELEASE_TOKEN || github.token }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: 'Lint Packages'
        run: npm run lint