name: "Setup"

on: 
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  setup:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-15']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.THE_GH_RELEASE_TOKEN || github.token }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools